# start_speed: 6400
# start_segments: 5

jump_speed: 6630
stop_speed: 6000

# ramp_up_time: 0.1
forward_time: 1.4
# air_time: 0.3


# measured dist | calculated dist | forward time | speed
# -------------------------------------------------------
#    1.0m             1.3m              1.4s       6630
#    0.5m             0.8m              1.7s       6465
# --------------------------------------------------------