# pid terms
pid: {
  kp: -50.0,
  ki: 0.0,
  kd: -5.0,
}
# control type
control_type: 'pid'
# turn direction - 'left' or 'right' when the robot is approaching a turn
turn_direction: 'left'
# threshold in meteres when the robot starts turning
turn_threshold: 2.5
# alpha - the FOV in degree within which the robot will look for a wall
alpha: 70
# normal_speed - the speed with which robot will normally drive
normal_speed: 6500
# turn_speed - the speed with which robot will drive while turning at sharp angles
turn_speed: 6150
